### ISSUE TITLE
16-Interactive-graphics duplicate examples

### ISSUE THREAD

**Issue by hwt** [rstudio/webinars#11]
07-data-structures.R is a duplicate of the 06-stopapp.R example instead of the code demoed in the data structure example.

**Comment by LuapRebel** [comment]
Could you please post the correct code for 07-data-structures.R?  As stated above, it is the same as 06-stopapp.R.  Thank you.

**Comment by wch** [comment]
Sorry for the long delay. It's fixed now. Hopefully you were able to find what you were looking for!
