### ISSUE TITLE
Cannot install nycflights13

### ISSUE THREAD

**Issue by ignacio82** [rstudio/webinars#2]
I'm having troubles installing `nycflights13`

```
install.packages("nycflights13")
Installing package into ‘/home/ignacio/R/x86_64-pc-linux-gnu-library/3.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘nycflights13’ is not available (for R version 3.0.2)
```

I'm running R on a Ubuntu 14.04 installation.

Thanks!

**Comment by bogus-e** [comment]
For some reason, I am getting this error with R 3.3.2 and the latest dplyr installed. The only place nycflights13 seems to exist my help file.

**Comment by jmclawson** [comment]
I have the same problem with 3.3.2, but I worked around it with this command: 
> install.packages("https://cran.r-project.org/src/contrib/nycflights13_0.2.2.tar.gz", repos=NULL, method="libcurl")

**Comment by decoursin** [comment]
@jmclawson thank you

**Comment by DBJP** [comment]
I also had the error with RStudio 1.0.143 (R x64 3.3.2 and 3.4.0 both appear to be installed on my system), but @jmclawson 's solution works for me: I can proceed with [R for Data Science Section 5.1](http://r4ds.had.co.nz/transform.html) without errors.

**Comment by sydneyg** [comment]
I had the same error as DBJP. Makes it hard to work through Hadley's R for Data Science book when NYCflights13 isn't compatible with the most recent installations of R and R studio!

**Comment by hadley** [comment]
Adding comments on a closed (and likely unrelated) issue is unlikely to get my attention.

You should be installing nycflights13 with `install.packages("nycflights13")`. The [CRAN page](https://cran.r-project.org/web/packages/nycflights13/index.html) shows binaries available for all platforms.

**Comment by rameez08** [comment]
thanks hadley! I was digging in github trying to use the import dataset function but this is much easier.

if you have the latest version of r and run install.packages("nycflights13") it should download the package

**Comment by sashikant123** [comment]
thanks!
i have a different kind of query, which is how to compile excel binary file. i have lots of excel binary file and sheets to compile and analyse.
thanks...

**Comment by stancsgp** [comment]
tawoodard, the file to install nycflights13 is not working

**Comment by stancsgp** [comment]
tawoodard, I managed to install "tibble" but when I try to install the nycflights13 package, there was an error: 
ERROR: dependency 'tibble' is not available for package 'nycflights13'
