### ISSUE TITLE
46-tidyverse-visualisation-and-manipulation-basics

### ISSUE THREAD

**Issue by vojtechhuser** [rstudio/webinars#28]
What is the link to the video recording of webinar 46?

The web archive is not organized by date and I am not able to find this Sep 2017 webinar.

Can you please post the link to it as reply here.
(or title on this page

![image](https://user-images.githubusercontent.com/7526119/31252048-eebe08a6-a9ed-11e7-89b8-7e0a7cf51665.png)

**Comment by garrettgman** [comment]
The link is: https://www.rstudio.com/resources/webinars/tidyverse-visualization-and-manipulation-basics/

You can find a list of the webinars by date if you expand the tab under the current webinar video, at the bottom right of  my screenshot. (I know: its subtle. We are working on a better way to curate these).

<img width="1062" alt="screen shot 2017-10-09 at 11 52 24 am" src="https://user-images.githubusercontent.com/85014/31346889-9a0aa488-ace8-11e7-80b7-d8dc3a0883d4.png">
