### ISSUE TITLE
13-R-Markdown-Ecosystem: how to embed webcam in HTML slides

### ISSUE THREAD

**Issue by benmarwick** [rstudio/webinars#37]
At about 31:08 in the [video](https://www.rstudio.com/resources/webinars/the-ecosystem-of-r-markdown/), @yihui shows that he can embed his webcam in a slidy presentation, and says it takes 3 lines of javascript. That's very cool to see! Are those three lines available to see somewhere?

**Comment by yihui** [comment]
Yes: https://yihui.name/en/2017/12/html5-camera/

**Comment by benmarwick** [comment]
That's wonderful, thanks!
