### ISSUE TITLE
53-databases-R

### ISSUE THREAD

**Issue by drkamarul** [rstudio/webinars#39]
Hi @edgararuiz, excellent webinar. I am using Windows 10 Home version on my laptop. I could not make a connection with the SQLEXPRESS::datawarehouse database, when I run

`library(odbc)`
`library(DBI)`
`con <- dbConnect(odbc(), 
                 Driver = "SQL Server", 
                 Server = "localhost\\SQLEXPRESS", 
                 Database = "datawarehouse", 
                 Trusted_Connection = "True")`

The RStudio just got stuck here

![image](https://user-images.githubusercontent.com/6749223/38168993-12ed5622-3590-11e8-82c7-630881abfde9.png)

This most probably happen because I do not have MS SQL Server. Is that right?

**Comment by edgararuiz** [comment]
Thanks.  That's right, you need to install MS SQL Express and also create, and populate, the database.  The last section of the RMarkdown document provides the link to where to download Express and the steps to download the data, create the database/schemata/tables and populate them.

**Comment by drkamarul** [comment]
Oh .. It is down there. My bad. Thanks very much @edgararuiz .
