### ISSUE TITLE
Post videos to YouTube

### ISSUE THREAD

**Issue by daattali** [rstudio/webinars#5]
I've discussed this with someone, potentially @garrettgman , a while ago, but I'd like to make it an "official" request because I still think it's a good idea.

You could have an RStudio YouTube user/channel that lists all your videos, which would make it easy for people to view all your webinars. YouTube is also nicer than Vimeo for lecture-type videos in my opinion because often times people like to watch lectures in 1.5x speed, which is not supported by Vimeo.

**Comment by carneybill** [comment]
Thanks...We are currently thinking about moving away from Vimeo but are not sure to where.  Wistia is an option we are considering.  Is the 1.5x feature the only feature that appeals to you?  Are there other things that come in handy when watching?

**Comment by timothyslau** [comment]
@carneybill , It seems like you're avoiding YouTube. Any particular reason?

**Comment by daattali** [comment]
YouTube also just feels familiar. Everybody knows YouTube and is used to it, which is also a small factor. You can also opt in/out of adding subtitles on YouTube. I do YouTube is the best option

**Comment by carneybill** [comment]
I wanted to provide a quick update.  The new Wistia player, built from the ground up on HTML5 allows speed and size control as well as has a thumbnail pane.  We are moving over to the new player this week hopefully. We aren't purposefully avoiding YouTube but Wistia gives us functionality and integrations YouTube doesn't.  I hope that the Wistia update helps, please let us know.

**Comment by daattali** [comment]
I just saw some RStudio webinars using the new Wistia player, and it is definitely a big improvement over the previous videos (I do appreciate being able to play at higher speeds and reduce the quality when I'm on a bad connection).  However, it still seems very far away from what YouTube is capable of providing and overall the experience of an embedded YouTube video is still much better in my opinion than Wistia.

That said, I do realize that I can only provide the perspective of the end user watching the videos, and I don't know what other considerations you have, such as the integrations you mentioned.  But for an end user I firmly believe YT is by far superior.  

Thanks for the update!

**Comment by pssguy** [comment]
I use the vembedr package  which makes it easy to embed videos from the services YouTube, Vimeo, and Microsoft Channel 9 (including useR! 2016 videos). Also allows setting start-time which I would definitely like to incorporate to highlight sections of your webinars on my blog . Any reason why you can't have the Wistia appraoch on your own site but also post to youtube?

**Comment by pgensler** [comment]
First, let me say that these webinars are truly enriching. I don't think I've learned more in 45 minutes by watching these talks to get me up and running with topics, so thank you.

I would agree that it makes sense to have a Youtube channel, as I think users know it already, thus making it much easier for someone to share with others; it's already in their current workflow (people binge on youtube).

Related, Is it possible to have an index in the Readme.md that links to each videos for each webinar? I find it very hard to navigate the current page to search for a particular Webinar for a topic (say rvest), and the readme.md file does not have an index, which I think would be a tremedous benefit. Having a search bar on the main page would be helpful so you could search for a tag to find a video about the concepts they cover, as I constantly refer back to these webinars:
https://www.rstudio.com/resources/webinars/

**Comment by carneybill** [comment]
Great news all.  We are almost ready to launch most of the current videos on our Youtube channel. We are also considering a live stream of several main sessions via Youtube at rstudio::conf 2018.

The workflow, discovery, and flexible organization issues are motivating factors. We are sacrificing some integrations but figured it would be worth the experiment.  Depending on how this works we might have the most recent videos (3 months perhaps?) hosted via Wistia on our site which will then migrate to Youtube once we hit the trigger date.

We would love additional feedback once the channel is updated.  Thanks for the input - @daattali , @pssguy , @pgensler

**Comment by pgensler** [comment]
@carneybill will the video's be unlisted(locked for certain viewers) on Youtube, or public?

**Comment by carneybill** [comment]
@pgensler They will be public.  Is there a reason we should consider locking some?

**Comment by pgensler** [comment]
No but I've seen it where other organizations lock the videos to make them unlisted on youtube, which makes it very hard to find and share with others.
